apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-monitor
  namespace: component-monitor
  labels:
    app: component-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-monitor
  template:
    metadata:
      labels:
        app: component-monitor
    spec:
      containers:
      - name: component-monitor
        image: quay.io/sgoeddel/component-monitor:latest
        env:
        - name: PROMETHEUS_URL
          value: "https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
        - name: KUBECONFIG
          value: "/etc/kubeconfig/app.ci.config"
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: kubeconfig
        secret:
          secretName: pod-scaler-kubeconfig
          items:
          - key: app.ci.config
            path: app.ci.config
          - key: sa.pod-scaler.app.ci.token.txt
            path: sa.pod-scaler.app.ci.token.txt
